### ISSUE TITLE
toolbox.c (how do you compile it?)

### ISSUE THREAD

**Issue by droidvoider** [freddierice/farm-root#3]
Solved enough for now, **please disregard**:

Looking for solution to same question?
After much research this what I think about compiling toolbox.c .. You can either setup a stand alone toolchain and then compile it on Ubuntu. Or you can compile it on a device with root. If you can compile it on a device with no root and a locked bootloader, that would surprise me, but I never believed it so I didn't research it. (as a matter of fact though you can just download header files in some cases, such as making a hack, or just short circuit the headers with faked ones..)

original question
If I try to compile things like toolbox I am always missing the headers. I Googled and googled on this subject, I see the questions asked but no one answers. ndk-build complains about **properties.h**, **selinux.h** and **tools.h**.. I think it wants specific versions from somewhere on my Samsung Note 5. I'm fairly sure that I can install a compiler on my device and compile it there.

I think it might be a shared library on my device. But if that's right I suck more at Google than I care to believe because I can't find anything to that effect.

updated:
I posted this question on XDA developers also but I don't think anyone will answer. I see this same questions asked over and over, on Google forums, on github. I don't know where to begin to understand this, if there was a book I'd buy it...

**Comment by freddierice** [comment]
I compiled it as a part of vanilla android.
