### ISSUE TITLE
not able to pull

### ISSUE THREAD

**Issue by TonyStark** [freddierice/farm-root#4]
after `make pull` nothing happen...

> make[1]: Leaving directory `/media/stark/afebc556-6185-4b48-81b3-bc81f3987dd8/farm-root'
> adb push toolbox_pull_boot /data/local/tmp/toolbox
> 1260 KB/s (101448 bytes in 0.078s)
> adb push libs/arm64-v8a/farm /data/local/tmp/farm
> 214 KB/s (10328 bytes in 0.046s)
> adb push till /data/local/tmp/till
> 31 KB/s (1341 bytes in 0.041s)
> adb push libs/arm64-v8a/bridge_pull_boot /data/local/tmp/bridge
> 208 KB/s (10256 bytes in 0.048s)
> adb shell chmod 0777 /data/local/tmp/bridge /data/local/tmp/till /data/local/tmp/farm /data/local/tmp/toolbox
> adb shell /data/local/tmp/farm
> 
> 

Here is `adb logcat` output

> 03-12 09:46:19.089 18369 18369 W dumpstate: type=1400 audit(0.0:10459): avc: denied { write } for name="recovery" dev="mmcblk0p25" ino=16385 scontext=u:r:dumpstate:s0 tcontext=u:object_r:cache_file:s0 tclass=dir permissive=0
> 03-12 09:46:25.200  3799 18485 W IcingInternalCorpora: getNumBytesRead when not calculated.
> 03-12 09:46:25.472  3799 18485 W IcingInternalCorpora: getNumBytesRead when not calculated.
> 03-12 09:46:45.549  1350  1406 E KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state: open failed: ENOENT (No such file or directory)
> 03-12 09:47:05.093  1350  1350 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1249 com.yulong.android.uitechno.service.YLUIWatchService.startComponent:1601 com.yulong.android.uitechno.service.YLUIWatchService$WatchHandler.handleMessage:1572 android.os.Handler.dispatchMessage:102 android.os.Looper.loop:148 
> 03-12 09:47:05.093  1350  1350 W ActivityManager: Unable to start service Intent { act=com.yulong.action.YLUIWatchService cmp=com.yulong.android.network.widget/.update.ControlUpdateManagerService } U=0: not found
> 03-12 09:47:34.305  1350  1406 E KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state: open failed: ENOENT (No such file or directory)
> 03-12 09:47:57.859  5066  5066 W perfd   : type=1400 audit(0.0:10460): avc: denied { kill } for capability=5 scontext=u:r:perfd:s0 tcontext=u:r:perfd:s0 tclass=capability permissive=0
> 03-12 09:47:57.859  5066  5066 W perfd   : type=1400 audit(0.0:10461): avc: denied { kill } for capability=5 scontext=u:r:perfd:s0 tcontext=u:r:perfd:s0 tclass=capability permissive=0

**Comment by freddierice** [comment]
It looks like your phone's manufacturer has a different set of selinux policies. You'll have to find another way to make it work.
